### ISSUE TITLE
TypeError: buildSettings.HEADER_SEARCH_PATHS.forEach is not a function

### ISSUE THREAD

**Issue by JulianKingman** [Elijen/react-native-fix-headers#1]
Firstly, thanks for this library! It's a big help with a tedious chore.

I get this error when running the script
```

/Users/Julian/.../node_modules/react-native-fix-headers/node_modules/xcode/lib/pbxProject.js:1287
        buildSettings['HEADER_SEARCH_PATHS'].forEach(function(existingFile){
                                             ^

TypeError: buildSettings.HEADER_SEARCH_PATHS.forEach is not a function
    at pbxProject.addToHeaderSearchPaths (/Users/Julian/.../node_modules/react-native-fix-headers/node_modules/xcode/lib/pbxProject.js:1287:46)
    at pbxProject.<anonymous> (/Users/Julian/.../node_modules/react-native-fix-headers/index.js:14:20)
    at pbxProject.emit (events.js:182:13)
    at pbxProject.<anonymous> (/Users/Julian/.../node_modules/react-native-fix-headers/node_modules/xcode/lib/pbxProject.js:48:18)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.3.20 fix-headers: `node `npm bin`/react-native-fix-headers`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.3.20 fix-headers script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Julian/.npm/_logs/2018-06-28T21_15_04_839Z-debug.log
```

**Comment by JulianKingman** [comment]
It seems that the buildSettings.HEADER_SEARCH_PATHS can be a string, so adding this:
```javascript
// hacky, I know
if (typeof buildSettings['HEADER_SEARCH_PATHS'] === 'string') {
  buildSettings['HEADER_SEARCH_PATHS'] = [buildSettings['HEADER_SEARCH_PATHS']]
}
```
before here: https://github.com/Elijen/cordova-node-xcode/blob/master/lib/pbxProject.js#L1287
Fixes it

**Comment by JulianKingman** [comment]
@Elijen would you take a PR?

**Comment by Elijen** [comment]
Hi @JulianKingman, glad somebody else finds it useful too. I think you are right. This commit https://github.com/Elijen/cordova-node-xcode/commit/9f2ec15c30b0ef5f2b1a708c79878c6251aa4046 was supposed to fix a similar issue, but I missed this case. 

PRs are indeed welcome.
